### ISSUE TITLE
Python Urlfetch Error: 'GET'

### ISSUE THREAD

**Issue by AlexWang90** [openimages/dataset#45] opened 2017-10-16 03:46 UTC
Hi:
      Is the dataset unable to download rescently? It returns "DownloadError('Unspecified error in fetching URL: https://storage.googleapis.com/openimages/2017_07/images_2017_07.tar.gz',), timeout=19" when I try to download the dataset from chrome and by using shell script the message is as following :
```
--2017-10-16 11:15:09--  https://storage.googleapis.com/openimages/2016_08/model_2016_08.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.27.144
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.27.144|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
```

**Comment by rkrasin** [comment] 2017-10-16 05:27
Works for me (tested right now)

Could it be something with the internet connectivity on your side?

**Comment by nalldrin** [comment] 2017-10-23 02:29
Also works for me, closing since not reproducible.

**Closed by nalldrin** 2017-10-23 02:29 UTC
